/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MeasurementRouteImport } from './routes/measurement'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as FabricationRouteImport } from './routes/fabrication'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as CurtainsSlugRouteImport } from './routes/curtains.$slug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiArticlesRouteImport } from './routes/api/articles'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementRoute = MeasurementRouteImport.update({
  id: '/measurement',
  path: '/measurement',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricationRoute = FabricationRouteImport.update({
  id: '/fabrication',
  path: '/fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CurtainsSlugRoute = CurtainsSlugRouteImport.update({
  id: '/curtains/$slug',
  path: '/curtains/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesRoute = ApiArticlesRouteImport.update({
  id: '/api/articles',
  path: '/api/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/fabrication': typeof FabricationRoute
  '/installation': typeof InstallationRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/measurement': typeof MeasurementRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/works': typeof WorksRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/content': typeof ApiContentRoute
  '/api/upload': typeof ApiUploadRoute
  '/curtains/$slug': typeof CurtainsSlugRoute
  '/post/$slug': typeof PostSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/fabrication': typeof FabricationRoute
  '/installation': typeof InstallationRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/measurement': typeof MeasurementRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/works': typeof WorksRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/content': typeof ApiContentRoute
  '/api/upload': typeof ApiUploadRoute
  '/curtains/$slug': typeof CurtainsSlugRoute
  '/post/$slug': typeof PostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/fabrication': typeof FabricationRoute
  '/installation': typeof InstallationRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/measurement': typeof MeasurementRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/works': typeof WorksRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/articles': typeof ApiArticlesRoute
  '/api/content': typeof ApiContentRoute
  '/api/upload': typeof ApiUploadRoute
  '/curtains/$slug': typeof CurtainsSlugRoute
  '/post/$slug': typeof PostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/consultation'
    | '/contact'
    | '/fabrication'
    | '/installation'
    | '/login'
    | '/maintenance'
    | '/measurement'
    | '/services'
    | '/sitemap.xml'
    | '/works'
    | '/admin'
    | '/api/articles'
    | '/api/content'
    | '/api/upload'
    | '/curtains/$slug'
    | '/post/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/consultation'
    | '/contact'
    | '/fabrication'
    | '/installation'
    | '/login'
    | '/maintenance'
    | '/measurement'
    | '/services'
    | '/sitemap.xml'
    | '/works'
    | '/admin'
    | '/api/articles'
    | '/api/content'
    | '/api/upload'
    | '/curtains/$slug'
    | '/post/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/consultation'
    | '/contact'
    | '/fabrication'
    | '/installation'
    | '/login'
    | '/maintenance'
    | '/measurement'
    | '/services'
    | '/sitemap.xml'
    | '/works'
    | '/_authenticated/admin'
    | '/api/articles'
    | '/api/content'
    | '/api/upload'
    | '/curtains/$slug'
    | '/post/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  FabricationRoute: typeof FabricationRoute
  InstallationRoute: typeof InstallationRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MeasurementRoute: typeof MeasurementRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorksRoute: typeof WorksRoute
  ApiArticlesRoute: typeof ApiArticlesRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiUploadRoute: typeof ApiUploadRoute
  CurtainsSlugRoute: typeof CurtainsSlugRoute
  PostSlugRoute: typeof PostSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurement': {
      id: '/measurement'
      path: '/measurement'
      fullPath: '/measurement'
      preLoaderRoute: typeof MeasurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrication': {
      id: '/fabrication'
      path: '/fabrication'
      fullPath: '/fabrication'
      preLoaderRoute: typeof FabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curtains/$slug': {
      id: '/curtains/$slug'
      path: '/curtains/$slug'
      fullPath: '/curtains/$slug'
      preLoaderRoute: typeof CurtainsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles': {
      id: '/api/articles'
      path: '/api/articles'
      fullPath: '/api/articles'
      preLoaderRoute: typeof ApiArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  FabricationRoute: FabricationRoute,
  InstallationRoute: InstallationRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  MeasurementRoute: MeasurementRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorksRoute: WorksRoute,
  ApiArticlesRoute: ApiArticlesRoute,
  ApiContentRoute: ApiContentRoute,
  ApiUploadRoute: ApiUploadRoute,
  CurtainsSlugRoute: CurtainsSlugRoute,
  PostSlugRoute: PostSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
